services:
    app:
        container_name: laravel-api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/app
            - ./docker-config/php.ini:/usr/local/etc/php/conf.d/php.ini
        ports:
            - "9000:9000"
        networks:
            - laravel_network

    nginx:
        container_name: laravel_nginx
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - db
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

volumes:
    db-data:

networks:
    laravel_network:
        driver: bridge
